### PR TITLE
Added screenshot of the RackUnit GUI, fixed typo.

### PR DESCRIPTION
**Pull request by jsmaniac**
Should I leave the program inside the screenshot, or should I trim it to only contain the RackUnit window?

### CODE REVIEW

**Comment by stamourv** [comment]
I'd just show the Rackunit window, since the code shows up right after in typeset form. I'd probably show the code first, though.

**Comment by jsmaniac** [comment]
@samth Updated, thanks for the input!

**Comment by stamourv** [comment]
@samth and I are in fact different people. I'm the better-looking of the two. ;)
Merged, thanks!

**Comment by jsmaniac** [comment]
Whoops, that was me typing faster than my own fingers. I knew shouldn't have installed auto-correct on my brain :) .

**Pull request merged**
