### PR TITLE
use paths of typed racket modules directly

### PR DESCRIPTION
**Pull request by capfredf**
related to https://github.com/racket/typed-racket/pull/1114/

### CODE REVIEW

**Comment by sorawee** [comment]
I think the right fix for `check-info-test.rkt` and `standalone.rkt` is provided by @AlexKnauth in #142

**Comment by capfredf** [comment]
Awesome. I will revert my fix.

**Comment by sorawee** [comment]
Yes, I think it can be merged. It doesn't cause more problems than what we already have.

**Comment by capfredf** [comment]
@sorawee can you help merge this pr?

**Comment by sorawee** [comment]
Unfortunately no, I don't have a right to do that. Perhaps ask @samth or @jackfirth?

**Pull request merged**
