### PR TITLE
moved rackunit/log to new pkg, fixed docs

### PR DESCRIPTION
**Pull request by florence**
Moving this to a new package lets packages like `redex` and `cover` depend on it without depending on all of rackunit.

### CODE REVIEW

**Comment by bennn** [comment]
Does this mean redex will eventually stop saying "Both tests passed" ? (I hope not)

**Comment by florence** [comment]
@bennn Nope! It just means that `redex` will report test counts and failures to `rackunit` (anything that uses those counts like `raco cover` and `raco test`).

**Comment by rfindler** [comment]
Wow, I am glad someone noticed! :)

**Comment by mflatt** [comment]
@florence A minor point, but is it ok if I change the author to "florence@racket-lang.org" to follow a weak convention of using racket-lang.org addresses for main-distribution packages?

**Comment by samth** [comment]
I don't think `florence@racket-lang.org` exists -- I think we mostly stopped adding new racket-lang.org addresses when everything moved to github.

**Comment by mflatt** [comment]
It looks to me like that address does exist.

**Comment by florence** [comment]
I didn't know that email was a thing, but I can confirm it reaches me. Do I change the author to "florence@racket-lang.org", or just 'florence?

**Comment by mflatt** [comment]
Just `'florence`

**Pull request closed without merging**
