### PR TITLE
test-case and test-begin should not catch ctrl-c's

### PR DESCRIPTION
**Pull request by florence**

### CODE REVIEW

**Comment by rfindler** [comment]
+1

Also: not-beak-exn?

**Comment by florence** [comment]
@rfindler `exn:not-break?` is in unstable it seems

**Comment by rfindler** [comment]
Wow, I guess that was only in my imagination?

**Comment by rfindler** [comment]
Maybe exn:fail?

**Comment by florence** [comment]
I think a `(raise 5)` should cause your test to fail, but not kill the rest of your tests.

**Comment by rfindler** [comment]
Ok by me.

**Comment by florence** [comment]
@rmculpepper Can I merge this for the release?

**Comment by rmculpepper** [comment]
Seems reasonable to me.

**Comment by florence** [comment]
I pushed as  2407b02

**Pull request closed without merging**
