### PR TITLE
Fixed check-within examples

### PR DESCRIPTION
**Pull request by matteo-daddio**
Hi sorawee, I followed your hints and I tried to fix the examples.

### CODE REVIEW

**Comment by sorawee** [comment]
Sorry if that was not clear: I already made the change. You can pull the latest version to see the updated content.

**Comment by matteo-daddio** [comment]
No problem sorawee.

Matteo d’Addio
________________________________
Da: sorawee ***@***.***>
Inviato: Monday, November 6, 2023 3:01:16 PM
A: racket/rackunit ***@***.***>
Cc: matteo-daddio ***@***.***>; Author ***@***.***>
Oggetto: Re: [racket/rackunit] Fixed check-within examples (PR #169)


Sorry if that was not clear: I already made the change. You can pull the latest version to see the updated content.

**Comment by matteo-daddio** [comment]
When will the rackunit documentation be updated?

Matteo d’Addio
________________________________
Da: sorawee ***@***.***>
Inviato: Monday, November 6, 2023 3:01:16 PM
A: racket/rackunit ***@***.***>
Cc: matteo-daddio ***@***.***>; Author ***@***.***>
Oggetto: Re: [racket/rackunit] Fixed check-within examples (PR #169)


Sorry if that was not clear: I already made the change. You can pull the latest version to see the updated content.

**Comment by sorawee** [comment]
RackUnit is a part of the main-distribution, so the main documentation is updated along the Racket release. Since your PR is merged after the 8.11 cut-off, the change will appear as a part of 8.12 (in ~3 months).

The snapshot documentation is already updated though. See e.g. https://plt.cs.northwestern.edu/snapshots/current/doc/rackunit/api.html#%28def._%28%28lib._rackunit%2Fmain..rkt%29._check-~3d%29%29

**Pull request closed without merging**
