### PR TITLE
rackunit/docs-complete: accept any `module-path?`

### PR DESCRIPTION
**Pull request by LiberalArtist**
This pull request updates the documentation to correspond to https://github.com/racket/racket/pull/2230

### CODE REVIEW

**Comment by rfindler** [comment]
Thanks., but this needs an `@history` annotation.

**Comment by bennn** [comment]
does it need a version bump too?

**Comment by bennn** [comment]
#102

**Comment by rfindler** [comment]
In principle, yes, but I don't think it really needs us to bother with a version bump, unless we know something is specifically depending on it (and wants to document that).

**Pull request merged**
